export const GET_POST_ACTION_REQUEST= "GET_POST_ACTION_REQUEST";
export const GET_POST_ACTION_SUCCESS= "GET_POST_ACTION_SUCCESS";
export const GET_POST_ACTION_FAIL= "GET_POST_ACTION_FAIL";

export const ADD_POST_ACTION_REQUEST= "ADD_POST_ACTION_REQUEST";
export const ADD_POST_ACTION_SUCCESS= "ADD_POST_ACTION_SUCCESS";
export const ADD_POST_ACTION_FAIL= "ADD_POST_ACTION_FAIL";

export const GET_POST_COMMENT_ACTION_REQUEST= "GET_POST_COMMENT_ACTION_REQUEST";
export const GET_POST_COMMENT_ACTION_SUCCESS= "GET_POST_COMMENT_ACTION_SUCCESS";
export const GET_POST_COMMENT_ACTION_FAIL= "GET_POST_COMMENT_ACTION_FAIL";

export const ADD_POST_COMMENT_ACTION_REQUEST= "ADD_POST_COMMENT_ACTION_REQUEST";
export const ADD_POST_COMMENT_ACTION_SUCCESS= "ADD_POST_COMMENT_ACTION_SUCCESS";
export const ADD_POST_COMMENT_ACTION_FAIL= "ADD_POST_COMMENT_ACTION_FAIL";

export const RESET_POST_COMMENT_ACTION= "RESET_POST_COMMENT_ACTION";



