export const SIGNIN_ACTION_REQUEST= "SIGNIN_ACTION_REQUEST";
export const SIGNIN_ACTION_SUCCESS= "SIGNIN_ACTION_SUCCESS";
export const SIGNIN_ACTION_FAIL= "SIGNIN_ACTION_FAIL";

export const SIGNUP_ACTION_REQUEST= "SIGNUP_ACTION_REQUEST";
export const SIGNUP_ACTION_SUCCESS= "SIGNUP_ACTION_SUCCESS";
export const SIGNUP_ACTION_FAIL= "SIGNUP_ACTION_FAIL";

export const SIGNOUT_ACTION_REQUEST= "SIGNOUT_ACTION_REQUEST";